name: Build
on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - run: dotnet build -c Release Domain0.Desktop\Domain0.Desktop.sln
